In [1]:
!pip install gensim
import pandas as pd
import gensim

In [2]:
train_data = pd.read_csv("train.csv")

In [3]:
train_data

id                                               text  label
0        train_0  "One would hope if I search for a word in the ...      0
1        train_1     "I would be beyond excited to get a response."      0
2        train_2  "Just like the user can select apps that are a...      1
3        train_3  "Once you create a CoreIndependentInputSource ...      0
4        train_4  "I Have problems with Contact class on Windows...      0
...          ...                                                ...    ...
5435  train_5435  "Instead we could get everything ready locally...      0
5436  train_5436  "This is so ridiculous that windows update doe...      0
5437  train_5437  We'll currently I have a Uwp app that needs to...      0
5438  train_5438  Also phone has support but is painful to use w...      0
5439  train_5439  "Allow a developer to read all notifications i...      1

[5440 rows x 3 columns]

In [4]:
test_data = pd.read_csv("test.csv")

In [5]:
train_data['text_clean'] = train_data['text'].apply(lambda x: gensim.utils.simple_preprocess(x))

test_data['text_clean'] = test_data['text'].apply(lambda x: gensim.utils.simple_preprocess(x))

In [6]:
X_train, y_train = train_data['text_clean'], train_data['label']
X_test, y_test = test_data['text_clean'], test_data['label']

In [7]:
w2v_model = gensim.models.Word2Vec(X_train,
                                   vector_size=200,
                                   window=10,
                                   min_count=4)

In [8]:
words = set(w2v_model.wv.index_to_key )

In [9]:
import numpy as np
X_train_vect = np.array([np.array([w2v_model.wv[i] for i in ls if i in words])
                         for ls in X_train])
X_test_vect = np.array([np.array([w2v_model.wv[i] for i in ls if i in words])
                         for ls in X_test])

C:\Users\Smitesh\AppData\Local\Temp/ipykernel_6796/294445517.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_train_vect = np.array([np.array([w2v_model.wv[i] for i in ls if i in words])
C:\Users\Smitesh\AppData\Local\Temp/ipykernel_6796/294445517.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_test_vect = np.array([np.array([w2v_model.wv[i] for i in ls if i in words])


In [10]:
X_train_vect_avg = []
for v in X_train_vect:
    if v.size:
        X_train_vect_avg.append(v.mean(axis=0))
    else:
        X_train_vect_avg.append(np.zeros(100, dtype=float))
        
X_test_vect_avg = []
for v in X_test_vect:
    if v.size:
        X_test_vect_avg.append(v.mean(axis=0))
    else:
        X_test_vect_avg.append(np.zeros(100, dtype=float))

In [16]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
NB_classifier_improv = GaussianNB()
NB_classifier_improv.fit(X_train_vect_avg, y_train)

C:\Users\Smitesh\anaconda3\envs\Main\lib\site-packages\sklearn\utils\validation.py:856: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  array = np.asarray(array, order=order, dtype=dtype)


ValueError: Expected 2D array, got 1D array instead:
array=[array([ 0.05670343, -0.09111831, -0.04821139,  0.20477964,  0.21512298,
        -0.42429078,  0.10782476,  0.5481424 , -0.09815809,  0.09922063,
        -0.24864024, -0.20187049,  0.02138986,  0.31912553, -0.1989246 ,
        -0.21178982, -0.10488376,  0.0202931 ,  0.05710293, -0.6166853 ,
         0.19334525, -0.40041623,  0.06707165,  0.10032443, -0.05437259,
        -0.2999239 , -0.03116014, -0.15634525, -0.28835827,  0.12482134,
         0.31628695,  0.00786004,  0.34017456, -0.03839939, -0.08561178,
         0.04103741,  0.27218163, -0.06395784, -0.12065346, -0.39127243,
        -0.24160011, -0.09507371, -0.09037808,  0.14372616,  0.52710116,
        -0.18012059, -0.11580903, -0.26678082,  0.17408589,  0.18000339,
         0.09608782, -0.19572881, -0.07939339, -0.31327614,  0.09789232,
        -0.13626817,  0.21120267, -0.2998412 , -0.44913673,  0.06114642,
        -0.2918708 ,  0.07040755,  0.01062978,  0.00350966, -0.5108059 ,
         0.17395164, -0.03836282,  0.5612781 , -0.34789994,  0.47999546,
        -0.06016533,  0.02297603,  0.4583262 , -0.05604641,  0.38370773,
         0.1473186 ,  0.31197205, -0.32321075, -0.6024053 , -0.10152726,
        -0.1308659 , -0.24026214, -0.35963508,  0.6044972 , -0.18632293,
        -0.11562271,  0.0526716 ,  0.22587472, -0.00558303,  0.01822955,
         0.38725075,  0.33907074,  0.3451539 ,  0.3863087 ,  0.62326384,
         0.4099045 ,  0.23822945, -0.10611782,  0.254828  ,  0.22517154,
        -0.22267024,  0.5177952 ,  0.2576123 , -0.02005129, -0.26051363,
        -0.55464125,  0.20523275,  0.31996036, -0.11348797, -0.47916713,
        -0.08105262, -0.2986138 , -0.22456867, -0.11158088,  0.19715963,
        -0.12256309,  0.34494644, -0.722926  , -0.00380875, -0.25881085,
        -0.09548991,  0.35601532,  0.37704188, -0.3295379 , -0.08014502,
         0.1580478 , -0.28468046,  0.01634474, -0.10550503, -0.13487062,
         0.20126696,  0.05321635, -0.0584072 , -0.22867638, -0.05464188,
         0.22272941, -0.17073953, -0.27505982, -0.07738592, -0.38953587,
         0.3519317 , -0.34301788, -0.16921793, -0.01755693, -0.06758733,
        -0.13301824, -0.30959675,  0.03402719,  0.11544834,  0.1768987 ,
         0.20752385, -0.31897706,  0.02231345,  0.09205893, -0.2167259 ,
         0.40963918,  0.2257581 ,  0.3282612 , -0.14616735,  0.22675848,
         0.25635844,  0.13991742,  0.03988382, -0.02706561,  0.07928919,
         0.2032313 ,  0.22540548, -0.03493557, -0.16289276,  0.2946744 ,
        -0.2913975 ,  0.13365191,  0.17765696, -0.15721944,  0.28623575,
         0.14102119, -0.2682203 ,  0.29637402,  0.20683518,  0.22551376,
        -0.01753959,  0.11034156,  0.1115704 ,  0.13941795,  0.07337555,
         0.14505932,  0.0824969 ,  0.33698934,  0.6929808 ,  0.2210886 ,
         0.34419143, -0.08091864, -0.24213696, -0.17044568,  0.06861529,
         0.18062523,  0.02956688, -0.36987174, -0.00555779, -0.10475206],
       dtype=float32)
 array([ 3.31349596e-02, -8.23114589e-02, -3.49546671e-02,  1.31585732e-01,
         1.53597996e-01, -2.75658935e-01,  7.13861138e-02,  3.71175498e-01,
        -6.05208911e-02,  7.50050321e-02, -1.66491151e-01, -1.43985748e-01,
         2.08152961e-02,  2.27811143e-01, -1.28162295e-01, -1.43881083e-01,
        -8.84360299e-02,  1.84389707e-02,  4.22900580e-02, -4.09022242e-01,
         1.26840577e-01, -2.77829707e-01,  4.80705164e-02,  6.50226623e-02,
        -3.69654670e-02, -1.93386883e-01,  6.48877816e-03, -1.20966390e-01,
        -1.93721026e-01,  8.28622580e-02,  2.06917092e-01, -6.35788869e-03,
         2.36521557e-01, -1.90870333e-02, -4.99571450e-02,  2.88571902e-02,
         1.80525973e-01, -3.27927060e-02, -7.94486031e-02, -2.83335865e-01,
        -1.65025339e-01, -7.16016218e-02, -8.14783722e-02,  1.10459827e-01,
         3.71715367e-01, -1.18430987e-01, -7.57904127e-02, -1.91335693e-01,
         1.29792258e-01,  1.16520874e-01,  6.86484724e-02, -1.53457806e-01,
        -5.33343926e-02, -2.19326109e-01,  6.84463158e-02, -7.63320848e-02,
         1.37501940e-01, -2.03884616e-01, -3.25456947e-01,  3.95261869e-02,
        -2.05564365e-01,  6.18754961e-02,  1.43030360e-02,  3.59005900e-03,
        -3.57963651e-01,  1.39779001e-01, -3.10143996e-02,  4.08805311e-01,
        -2.43546858e-01,  3.46153229e-01, -2.70644296e-02,  2.77503021e-02,
         3.28302562e-01, -5.48561402e-02,  2.73015887e-01,  1.09975182e-01,
         2.32844561e-01, -2.37585455e-01, -4.17228490e-01, -7.52943158e-02,
        -9.96445268e-02, -1.67777151e-01, -2.60186702e-01,  3.92090499e-01,
        -1.29872665e-01, -8.36430788e-02,  2.29421258e-02,  1.37056500e-01,
         3.88762960e-03,  9.03883018e-04,  2.63970882e-01,  2.20931441e-01,
         2.45243341e-01,  2.79394299e-01,  4.19565111e-01,  2.98044771e-01,
         1.75878882e-01, -7.61629194e-02,  1.65010780e-01,  1.50745898e-01,
        -1.50179550e-01,  3.83233935e-01,  1.63797900e-01, -2.90122647e-02,
        -1.78866133e-01, -4.13869113e-01,  1.52386323e-01,  2.34174937e-01,
        -8.43235701e-02, -3.59858274e-01, -4.29455563e-02, -2.09388256e-01,
        -1.56974167e-01, -9.73619297e-02,  1.54869080e-01, -9.20368880e-02,
         2.49946743e-01, -5.17348945e-01,  6.88699260e-03, -1.66867390e-01,
        -6.25681728e-02,  2.38004282e-01,  2.68296063e-01, -2.36666337e-01,
        -6.71848580e-02,  1.03721201e-01, -2.01836273e-01, -8.74653365e-03,
        -6.70628697e-02, -1.05819896e-01,  1.36615276e-01,  3.29707973e-02,
        -3.89820896e-02, -1.58113912e-01, -3.50137539e-02,  1.74418479e-01,
        -1.19724214e-01, -1.75775275e-01, -6.16810247e-02, -2.77656764e-01,
         2.50193685e-01, -2.34207377e-01, -1.08831331e-01, -8.04155134e-05,
        -4.57644872e-02, -1.01045534e-01, -2.11604908e-01,  1.59509685e-02,
         6.60213307e-02,  1.22261718e-01,  1.38808414e-01, -2.08670393e-01,
         2.72873025e-02,  5.36358990e-02, -1.31369114e-01,  2.69369096e-01,
         1.53823614e-01,  2.19139501e-01, -9.28754658e-02,  1.48199528e-01,
         1.64083153e-01,  8.81338269e-02,  2.59032156e-02, -9.09652654e-03,
         7.00899437e-02,  1.45625979e-01,  1.60969332e-01, -1.44887064e-02,
        -1.19408898e-01,  2.03154683e-01, -1.95029631e-01,  7.85367042e-02,
         1.43511698e-01, -9.69106406e-02,  2.08121657e-01,  1.15482070e-01,
        -1.85609460e-01,  2.12630168e-01,  1.32779732e-01,  1.76533580e-01,
        -2.32690070e-02,  9.94835645e-02,  8.51440504e-02,  9.60947126e-02,
         5.91765866e-02,  1.04442015e-01,  7.07598403e-02,  2.48451725e-01,
         4.96327370e-01,  1.36974335e-01,  2.41115168e-01, -5.13647199e-02,
        -1.73864871e-01, -1.32026747e-01,  5.21371961e-02,  1.12011135e-01,
         1.17468629e-02, -2.59787112e-01,  1.26153836e-02, -8.43274966e-02],
       dtype=float32)
 array([ 5.67630343e-02, -9.34960842e-02, -4.90066335e-02,  2.00837195e-01,
         2.14808211e-01, -4.15327311e-01,  1.07860409e-01,  5.44358194e-01,
        -9.64495912e-02,  9.97482166e-02, -2.45041564e-01, -1.99780777e-01,
         2.47353334e-02,  3.19164008e-01, -1.93116203e-01, -2.08539471e-01,
        -1.07229508e-01,  2.15223748e-02,  5.58449291e-02, -6.06359124e-01,
         1.89055696e-01, -3.97233009e-01,  6.52358979e-02,  9.72881094e-02,
        -5.39368875e-02, -2.95869589e-01, -2.42003482e-02, -1.61287874e-01,
        -2.85220414e-01,  1.22779556e-01,  3.08363020e-01,  8.35355662e-04,
         3.38138789e-01, -3.65636013e-02, -8.30292925e-02,  4.21241596e-02,
         2.67423451e-01, -6.02910370e-02, -1.17086262e-01, -3.91030461e-01,
        -2.39008322e-01, -9.58831906e-02, -9.26813856e-02,  1.48608223e-01,
         5.24630368e-01, -1.74344227e-01, -1.15155399e-01, -2.64124125e-01,
         1.73821077e-01,  1.75722539e-01,  9.55593213e-02, -2.00482517e-01,
        -7.89755806e-02, -3.13057512e-01,  9.75079536e-02, -1.30291998e-01,
         2.05950320e-01, -2.93028146e-01, -4.47580338e-01,  6.03191815e-02,
        -2.88583428e-01,  7.45549947e-02,  1.15429275e-02,  3.07270605e-03,
        -5.04849136e-01,  1.77196503e-01, -3.82182151e-02,  5.63081682e-01,
        -3.42446893e-01,  4.76358086e-01, -5.79232313e-02,  2.54738834e-02,
         4.58972603e-01, -5.77798374e-02,  3.85675639e-01,  1.49281204e-01,
         3.11490566e-01, -3.24062973e-01, -5.97372234e-01, -1.04241937e-01,
        -1.33037999e-01, -2.39962474e-01, -3.62250775e-01,  5.94305694e-01,
        -1.83870539e-01, -1.16573162e-01,  4.61773984e-02,  2.20807388e-01,
        -3.50636966e-03,  1.25802932e-02,  3.84148598e-01,  3.33406627e-01,
         3.45606387e-01,  3.87552500e-01,  6.19780898e-01,  4.09949124e-01,
         2.39286825e-01, -1.02381468e-01,  2.49729633e-01,  2.18569055e-01,
        -2.15047747e-01,  5.19782126e-01,  2.53460079e-01, -2.21847799e-02,
        -2.54785419e-01, -5.56400418e-01,  2.10380286e-01,  3.21676999e-01,
        -1.14687979e-01, -4.80549157e-01, -7.65558034e-02, -2.95335263e-01,
        -2.20249683e-01, -1.17193542e-01,  1.98463276e-01, -1.21769845e-01,
         3.43217194e-01, -7.18719840e-01, -2.70905811e-03, -2.54196674e-01,
        -9.41780210e-02,  3.48945588e-01,  3.71756613e-01, -3.28227729e-01,
        -8.17828104e-02,  1.55805975e-01, -2.81429708e-01,  1.13618569e-02,
        -1.05693869e-01, -1.36250570e-01,  1.98818967e-01,  5.19074462e-02,
        -5.59152700e-02, -2.28223130e-01, -5.45256510e-02,  2.25971803e-01,
        -1.67279840e-01, -2.65809417e-01, -7.80997872e-02, -3.87553722e-01,
         3.49952787e-01, -3.39757770e-01, -1.63727403e-01, -1.16727315e-02,
        -6.60503060e-02, -1.33101434e-01, -3.05699646e-01,  3.00703011e-02,
         1.10211842e-01,  1.74267843e-01,  2.03350350e-01, -3.13789725e-01,
         2.36584675e-02,  8.67733285e-02, -2.08904639e-01,  3.98027003e-01,
         2.20142037e-01,  3.23024780e-01, -1.39719799e-01,  2.22687051e-01,
         2.48440310e-01,  1.36355564e-01,  4.08602133e-02, -2.69935243e-02,
         8.18492770e-02,  2.02527985e-01,  2.24834383e-01, -3.05681825e-02,
        -1.66545257e-01,  2.90321767e-01, -2.88521856e-01,  1.30042136e-01,
         1.82106391e-01, -1.52366206e-01,  2.85257131e-01,  1.41035229e-01,
        -2.65403092e-01,  2.93343514e-01,  2.00641543e-01,  2.31209368e-01,
        -1.86269637e-02,  1.16722316e-01,  1.10073090e-01,  1.39851078e-01,
         7.31176212e-02,  1.46795049e-01,  8.57781842e-02,  3.36260855e-01,
         6.90566599e-01,  2.13069871e-01,  3.39837670e-01, -7.90726617e-02,
        -2.42339104e-01, -1.69621274e-01,  6.98203072e-02,  1.71001017e-01,
         2.72362791e-02, -3.66934210e-01,  5.91279240e-04, -1.08886868e-01],
       dtype=float32)
 ...
 array([ 0.0539064 , -0.08246115, -0.04421888,  0.19287898,  0.20043367,
        -0.38981968,  0.09866843,  0.5095265 , -0.0913475 ,  0.09370089,
        -0.22916876, -0.18330754,  0.02309204,  0.29615986, -0.17781295,
        -0.19287205, -0.09589274,  0.01751673,  0.05475397, -0.5693963 ,
         0.17797564, -0.36745015,  0.05628808,  0.09012563, -0.04666378,
        -0.2821983 , -0.03302087, -0.14683379, -0.26998433,  0.11501452,
         0.2889694 ,  0.00327925,  0.31169432, -0.03497347, -0.07897875,
         0.04013759,  0.25257394, -0.06315675, -0.1114905 , -0.3582765 ,
        -0.22370179, -0.0900127 , -0.08108884,  0.13665189,  0.48863977,
        -0.16400002, -0.10967189, -0.2442599 ,  0.15713602,  0.16576289,
         0.08615049, -0.18190786, -0.07323363, -0.2921913 ,  0.09129985,
        -0.1264361 ,  0.19527319, -0.27413484, -0.41423473,  0.05491062,
        -0.26664686,  0.06585864,  0.01176038,  0.0022126 , -0.47170427,
         0.15916237, -0.03345485,  0.5200315 , -0.3174419 ,  0.43858102,
        -0.05955797,  0.01839837,  0.42625076, -0.04913637,  0.35766575,
         0.13413239,  0.28413552, -0.2974045 , -0.5594084 , -0.09463322,
        -0.12022846, -0.22399229, -0.334243  ,  0.565976  , -0.1686688 ,
        -0.10657226,  0.04643821,  0.2138169 , -0.00329331,  0.01389621,
         0.3604504 ,  0.3147546 ,  0.31773376,  0.35429865,  0.5805789 ,
         0.37945208,  0.21965832, -0.09222787,  0.2393837 ,  0.20544788,
        -0.20059308,  0.4769069 ,  0.24237268, -0.01606058, -0.23968638,
        -0.5073297 ,  0.19183338,  0.2946564 , -0.10363832, -0.43725368,
        -0.0746178 , -0.2731527 , -0.20586795, -0.10232892,  0.17830785,
        -0.1135515 ,  0.31769273, -0.66865456, -0.00463805, -0.24042304,
        -0.08529498,  0.33040866,  0.34356904, -0.2993251 , -0.0739046 ,
         0.14545314, -0.26005146,  0.01727633, -0.09978811, -0.12158003,
         0.1889649 ,  0.04944552, -0.0553406 , -0.21331805, -0.05255904,
         0.20726898, -0.15486437, -0.25389025, -0.07069361, -0.3614656 ,
         0.32129017, -0.3176858 , -0.15610883, -0.0153612 , -0.06249039,
        -0.11943718, -0.28434008,  0.03300058,  0.10893455,  0.16442394,
         0.19254324, -0.29396695,  0.01282497,  0.08109272, -0.20221528,
         0.37734696,  0.20879152,  0.30742672, -0.12806667,  0.21072865,
         0.23468402,  0.13255088,  0.04152557, -0.02769013,  0.07199409,
         0.18533315,  0.2071231 , -0.0315387 , -0.15150467,  0.26939613,
        -0.2731773 ,  0.1297107 ,  0.16215985, -0.14676516,  0.2634376 ,
         0.12241195, -0.24614003,  0.27319437,  0.19046003,  0.21072459,
        -0.01052245,  0.09966502,  0.10309115,  0.13076374,  0.06754658,
         0.1348829 ,  0.07282673,  0.30782703,  0.63909775,  0.2081177 ,
         0.31665045, -0.07452694, -0.21980788, -0.15504119,  0.06570435,
         0.16289625,  0.03011486, -0.34060985, -0.00311784, -0.09869893],
       dtype=float32)
 array([ 0.05464053, -0.08726189, -0.04448687,  0.20241088,  0.21685712,
        -0.41698423,  0.10924529,  0.54529124, -0.09847347,  0.09860365,
        -0.24585769, -0.1984832 ,  0.0242182 ,  0.3145023 , -0.19374949,
        -0.21069679, -0.1041586 ,  0.02078408,  0.05674925, -0.60903233,
         0.1877688 , -0.39198548,  0.06321958,  0.0974914 , -0.04901363,
        -0.29731333, -0.03249593, -0.15806745, -0.28707188,  0.12185378,
         0.3098861 ,  0.00142718,  0.33627144, -0.03469485, -0.08401515,
         0.04096105,  0.27127266, -0.06248051, -0.11712575, -0.38820273,
        -0.24005194, -0.09224588, -0.09072608,  0.14647862,  0.5230518 ,
        -0.1783837 , -0.11494891, -0.26192877,  0.16887474,  0.17696217,
         0.09204482, -0.19460428, -0.07801704, -0.31496027,  0.09694711,
        -0.13560982,  0.20738195, -0.29516977, -0.44327804,  0.05657132,
        -0.2854952 ,  0.06963525,  0.01255805,  0.0015782 , -0.50862956,
         0.1713776 , -0.03618863,  0.5575254 , -0.3396933 ,  0.47130445,
        -0.06367785,  0.0234118 ,  0.45533302, -0.05068447,  0.38152415,
         0.1475253 ,  0.30519238, -0.32145026, -0.5997022 , -0.09975766,
        -0.12822843, -0.23994598, -0.35732523,  0.6000993 , -0.18383838,
        -0.11429721,  0.04814853,  0.22329369, -0.00630163,  0.01550337,
         0.38436955,  0.33487806,  0.34271905,  0.3806416 ,  0.6230449 ,
         0.40629137,  0.23530519, -0.10089327,  0.25506228,  0.21615595,
        -0.21596527,  0.51490545,  0.25452155, -0.01757283, -0.25319314,
        -0.5490571 ,  0.20381014,  0.31912637, -0.11336722, -0.4710319 ,
        -0.07726949, -0.29263464, -0.2202932 , -0.11383387,  0.19317399,
        -0.12027906,  0.3417204 , -0.7148402 , -0.00191632, -0.255933  ,
        -0.09375253,  0.35068536,  0.37262565, -0.32130554, -0.07677457,
         0.15392652, -0.27754503,  0.01920999, -0.10705501, -0.13397343,
         0.19972518,  0.04972334, -0.05847597, -0.22640532, -0.05803334,
         0.2230234 , -0.16534793, -0.27093205, -0.07481696, -0.38337877,
         0.34695202, -0.33947346, -0.16628215, -0.01577353, -0.06823549,
        -0.12671646, -0.303998  ,  0.03529621,  0.11466208,  0.1741985 ,
         0.20517288, -0.31371796,  0.01616539,  0.0872739 , -0.2136978 ,
         0.3970536 ,  0.22194543,  0.32696447, -0.13606057,  0.22196372,
         0.25019258,  0.1405171 ,  0.04359907, -0.02688621,  0.08062644,
         0.198046  ,  0.22571838, -0.03319174, -0.16420227,  0.28796408,
        -0.2899977 ,  0.13663486,  0.17430916, -0.15452878,  0.28204435,
         0.13534544, -0.26696602,  0.29296398,  0.20541702,  0.22691157,
        -0.01602049,  0.11038881,  0.11095046,  0.14095183,  0.07021023,
         0.14514466,  0.07936349,  0.3312553 ,  0.6857941 ,  0.21958889,
         0.33771235, -0.07926476, -0.23907274, -0.16631041,  0.07047901,
         0.172649  ,  0.02951282, -0.3652736 , -0.00312651, -0.10718261],
       dtype=float32)
 array([ 0.05786549, -0.08537965, -0.04503566,  0.19404772,  0.2072388 ,
        -0.40165505,  0.09969348,  0.51977444, -0.09706886,  0.09585303,
        -0.23869403, -0.19091794,  0.02190062,  0.30669713, -0.18738833,
        -0.19910309, -0.09760309,  0.01473455,  0.05256939, -0.58669174,
         0.18239161, -0.37695536,  0.06344766,  0.09312063, -0.04817967,
        -0.28812867, -0.03091083, -0.14497569, -0.27491826,  0.12018538,
         0.2986347 ,  0.00613064,  0.31884497, -0.03540245, -0.08531205,
         0.03844073,  0.2583626 , -0.06398554, -0.11795124, -0.36832446,
        -0.23173663, -0.08755775, -0.08577818,  0.13950014,  0.50282353,
        -0.1690344 , -0.11064887, -0.25309116,  0.16656043,  0.17131367,
         0.08947502, -0.18536225, -0.07853834, -0.2941808 ,  0.09137194,
        -0.13393965,  0.20030808, -0.2846726 , -0.42714986,  0.05574642,
        -0.27417782,  0.06627312,  0.00864404,  0.00215122, -0.48387632,
         0.16222298, -0.03325048,  0.5299696 , -0.32617888,  0.4501763 ,
        -0.05971299,  0.0213634 ,  0.43043423, -0.05268092,  0.3624757 ,
         0.14080095,  0.29460225, -0.30119854, -0.56842107, -0.0950949 ,
        -0.11950339, -0.22620817, -0.33704776,  0.5730385 , -0.1744833 ,
        -0.10870458,  0.0453689 ,  0.21588127, -0.00518278,  0.01556924,
         0.3652964 ,  0.3239116 ,  0.3261812 ,  0.35981292,  0.59060955,
         0.3869217 ,  0.22609   , -0.09784222,  0.24491227,  0.21247748,
        -0.2154572 ,  0.49078035,  0.24887796, -0.01786071, -0.24655788,
        -0.523033  ,  0.19792601,  0.3052005 , -0.10234301, -0.4490705 ,
        -0.07628004, -0.27918714, -0.20839791, -0.1039557 ,  0.18543634,
        -0.11886561,  0.32163513, -0.6808106 , -0.005428  , -0.24585673,
        -0.08965678,  0.33587533,  0.3527858 , -0.30930945, -0.07681024,
         0.14998505, -0.26683858,  0.01750907, -0.10191728, -0.12631036,
         0.18958764,  0.05276644, -0.05930709, -0.21669726, -0.05302991,
         0.20969887, -0.15774837, -0.2643885 , -0.06948002, -0.36777148,
         0.334003  , -0.32398453, -0.16311292, -0.02024714, -0.06478836,
        -0.12436582, -0.29077783,  0.03268319,  0.11193021,  0.16741261,
         0.19874449, -0.3057217 ,  0.01839579,  0.08536797, -0.20740657,
         0.39078954,  0.21416514,  0.31327116, -0.13702431,  0.21577032,
         0.24628076,  0.13654561,  0.03966539, -0.03188567,  0.07447005,
         0.19037776,  0.21116379, -0.0319121 , -0.15287562,  0.27420056,
        -0.27619064,  0.13121648,  0.1641387 , -0.14614342,  0.2695869 ,
         0.12946048, -0.2524288 ,  0.28140756,  0.1967619 ,  0.21024151,
        -0.01433375,  0.1006052 ,  0.10763385,  0.13173711,  0.06543388,
         0.13485691,  0.07866239,  0.31542036,  0.6548375 ,  0.20762952,
         0.32560664, -0.07415746, -0.22661611, -0.16077709,  0.06852521,
         0.1689597 ,  0.03288204, -0.35004947, -0.00789482, -0.09823976],
       dtype=float32)                                                    ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
y_pred = NB_classifier_improv.predict(X_test_vect_avg)

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))